# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6111c640611fba011f862610c7b63fddb761a4a45b5b61e1eaaa0fd4e0d3b2fdc39731f7fae163efc8ab9d29778e43f7b15f810e78333119c7df014e6fe5d40

test:
  secret_key_base: 03f40ff5b288e71028f11d7dd4828b8f7df849ae8473aafb93a0c54563189b4d3a8558c32ab70d6e47e6a59a3d602b4311396e99f63da6c6489f1c407c2331d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
